server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:alleviare_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:AlleviarePassword123!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
