import 'package:flutter/material.dart';
import '../models/user_model.dart';
import '../models/doctor_model.dart';
import '../models/chemist_model.dart';
import '../models/stockist_model.dart';
import '../models/product_model.dart';
import '../models/dcr_model.dart';
import '../models/pob_order_model.dart';
import '../models/rcpa_model.dart';
import '../models/tour_plan_model.dart';
import '../models/sample_inventory_model.dart';
import '../models/expense_model.dart';
import '../models/facility_model.dart';

class MockDataService {
  static UserModel getInitialUser() => UserModel(
        id: 'mr_101',
        empCode: 'EMP-MR-7842',
        name: 'Sokha Chea',
        email: 'sokha.chea@alleviarepharma.com',
        phone: '+855 23 888 999',
        emergencyContact: 'Sophea Chea (Spouse) • +855 12 345 678',
        designation: 'Senior Medical Representative (SMR)',
        department: 'Cardiovascular & Specialty Therapeutics',
        division: 'Cardio-Ortho Division',
        company: 'Alleviare Life Sciences Pvt. Ltd.',
        dateOfJoining: '15 March 2022',
        employeeStatus: 'Active',
        regionZone: 'South-East Asia / Phnom Penh Central Zone',
        headquarters: 'Phnom Penh Central HQ',
        territory: 'Zone 1 - Central Hospital & Beat Patches',
        managerName: 'Rajesh Sharma (Area Sales Manager)',
        managerPhone: '+855 23 999 111',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        startOdometerKm: 14230.0,
        workType: 'Field Work',
      );

  static List<ProductModel> getProducts() => [
        ProductModel(
          id: 'prod_1',
          brandName: 'CardioVasc-AM',
          genericName: 'Telmisartan 40mg + Amlodipine 5mg Tablets',
          therapeuticCategory: 'Cardiology',
          dosageForm: 'Tablets (Bi-layered)',
          packing: '10 x 10 Blister Pack',
          mrp: 14.50,
          ptr: 10.50,
          pts: 9.50,
          gstRate: 10.0,
          currentScheme: '10 + 1 Free',
          indication: 'Essential Hypertension & Cardiovascular Risk Reduction',
          isFocusBrand: true,
          sampleStock: 45,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'CardioVasc-AM',
              subtitle: 'The 24-Hour Superior Blood Pressure Control',
              clinicalClaim: 'Proven 24.8 mmHg reduction in Mean SBP over 24-hour ambulatory monitoring.',
              bulletPoints: ['Longest half-life (24h) ensures morning surge protection.', 'Selective AT1 receptor blocker.', 'High safety profile.'],
              dosageInfo: '1 tablet once daily in morning.',
              mechanismOfAction: 'Telmisartan selectively blocks AT1 receptors; Amlodipine inhibits Calcium influx.',
              keyUsp: '24-Hour Sustained Action • Zero Pedal Edema',
              slideThemeColor: const Color(0xFF0D9488),
              statsHighlight: {'SBP Reduction': '-24.8 mmHg', 'Half Life': '24 Hours', 'Target BP Goal': '88%'},
            ),
          ],
        ),
        ProductModel(
          id: 'prod_2',
          brandName: 'GlycoSmart-D10',
          genericName: 'Dapagliflozin 10mg + Metformin 1000mg ER Tablets',
          therapeuticCategory: 'Diabetology',
          dosageForm: 'Extended Release Tablets',
          packing: '10 x 10 Alu-Alu Pack',
          mrp: 23.50,
          ptr: 16.80,
          pts: 15.10,
          gstRate: 10.0,
          currentScheme: '10 + 2 Free',
          indication: 'Type 2 Diabetes Mellitus with Cardio-Renal Benefits',
          isFocusBrand: true,
          isNewLaunch: true,
          sampleStock: 30,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'GlycoSmart-D10',
              subtitle: 'Dual-Engine Glycemic Control & Cardiorenal Shield',
              clinicalClaim: 'Achieves robust HbA1c reduction of 1.75% with weight loss benefit.',
              bulletPoints: ['High selective SGLT-2 inhibition.', 'Metformin ER minimizes GI distress.', '32% RRR in HF hospitalizations.'],
              dosageInfo: 'One tablet once daily with morning meal.',
              mechanismOfAction: 'Inhibits renal glucose reabsorption + reduces hepatic glucose output.',
              keyUsp: 'Glycemic Control • Cardiorenal Protection',
              slideThemeColor: const Color(0xFF6366F1),
              statsHighlight: {'HbA1c Drop': '-1.75%', 'HF Hospitalization': '-32%', 'Weight Loss': '-3.2 kg'},
            ),
          ],
        ),
        ProductModel(
          id: 'prod_3',
          brandName: 'Cefomax-CV 325',
          genericName: 'Cefpodoxime Proxetil 200mg + Potassium Clavulanate 125mg',
          therapeuticCategory: 'Antibiotics',
          dosageForm: 'Film Coated Tablets',
          packing: '1 x 10 Strip in Monocarton',
          mrp: 31.00,
          ptr: 22.00,
          pts: 19.80,
          gstRate: 10.0,
          currentScheme: '10 + 1 Free',
          indication: 'Resistant RTIs, UTIs, and Soft Tissue Infections',
          isFocusBrand: false,
          sampleStock: 25,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'Cefomax-CV 325',
              subtitle: 'The Shield Against Beta-Lactamase Resistance',
              clinicalClaim: '94.6% clinical cure rate in Community Acquired Pneumonia.',
              bulletPoints: ['Broad spectrum bactericidal coverage.', 'Clavulanate overcomes ESBL resistance.', 'Excellent tissue penetration.'],
              dosageInfo: '1 tablet twice daily after meals for 5-7 days.',
              mechanismOfAction: 'Inhibits bacterial cell wall synthesis while neutralizing beta-lactamases.',
              keyUsp: 'Proven ESBL Coverage • High Bioavailability',
              slideThemeColor: const Color(0xFF0284C7),
              statsHighlight: {'Cure Rate': '94.6%', 'Tissue Peak': '2.8 mcg/mL', 'ESBL Active': '99%'},
            ),
          ],
        ),
        ProductModel(
          id: 'prod_4',
          brandName: 'PanSafe-DSR',
          genericName: 'Pantoprazole 40mg + Domperidone 30mg SR Capsules',
          therapeuticCategory: 'Gastroenterology',
          dosageForm: 'Sustained Release Capsules',
          packing: '10 x 10 Alu-Alu Pack',
          mrp: 14.50,
          ptr: 10.20,
          pts: 9.18,
          gstRate: 10.0,
          currentScheme: '10 + 2 Free',
          indication: 'GERD, Reflux Esophagitis, Non-Ulcer Dyspepsia',
          isFocusBrand: false,
          sampleStock: 50,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'PanSafe-DSR',
              subtitle: 'Rapid Relief from Acid Surge & Dysmotility',
              clinicalClaim: 'Fast onset within 15 minutes with 24-hour acid suppression.',
              bulletPoints: ['Dual-pellet release technology.', 'Rapid gastric emptying with Domperidone SR.', 'Zero food-drug interaction.'],
              dosageInfo: '1 capsule daily 30 minutes before breakfast.',
              mechanismOfAction: 'Inhibits H+/K+ ATPase pump + D2 receptor antagonism.',
              keyUsp: 'Quick Daytime & Night-time Heartburn Relief',
              slideThemeColor: const Color(0xFFEA580C),
              statsHighlight: {'Onset': '< 15 Mins', '24h pH > 4': '18.4 Hours', 'Relief Score': '96%'},
            ),
          ],
        ),
        ProductModel(
          id: 'prod_5',
          brandName: 'OsteoFlex-D3 Max',
          genericName: 'Calcium Carbonate 1250mg + Calcitriol 0.25mcg + Zinc + Boron',
          therapeuticCategory: 'Orthopedics',
          dosageForm: 'Soft Gelatin Capsules',
          packing: '3 x 10 Blister in Monocarton',
          mrp: 18.50,
          ptr: 13.20,
          pts: 11.88,
          gstRate: 10.0,
          currentScheme: '10 + 1 Free',
          indication: 'Osteoporosis, Post-Menopausal Bone Loss, Fracture Healing',
          isFocusBrand: false,
          sampleStock: 40,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'OsteoFlex-D3 Max',
              subtitle: 'Comprehensive Bone Mineralization & Strength',
              clinicalClaim: 'Increases Bone Mineral Density (BMD) by 4.8% in 6 months.',
              bulletPoints: ['Active Calcitriol ensures 3x higher calcium absorption.', 'Zinc & Boron stimulate osteoblast differentiation.', 'Zero gastrointestinal bloating.'],
              dosageInfo: '1 softgel daily after dinner.',
              mechanismOfAction: 'Enhances intestinal Ca2+ absorption and stimulates bone mineralization matrix.',
              keyUsp: 'High Bioavailability • Superior BMD Gains',
              slideThemeColor: const Color(0xFF16A34A),
              statsHighlight: {'BMD Increase': '+4.8%', 'Ca Absorption': '3.2x', 'Fracture Risk': '-38%'},
            ),
          ],
        ),
        ProductModel(
          id: 'prod_6',
          brandName: 'Lubrica-Forte',
          genericName: 'Glucosamine Sulfate 750mg + Chondroitin Sulfate 400mg + Collagen Peptides',
          therapeuticCategory: 'Orthopedics',
          dosageForm: 'Effervescent Sachets',
          packing: '10 Sachets / Box',
          mrp: 42.00,
          ptr: 30.00,
          pts: 27.00,
          gstRate: 10.0,
          currentScheme: '10 + 1 Free',
          indication: 'Joint Cartilage Regeneration & Osteoarthritis Pain',
          isFocusBrand: true,
          sampleStock: 20,
          visualAidSlides: [
            VisualAidSlide(
              slideNumber: 1,
              title: 'Lubrica-Forte',
              subtitle: 'Advanced Joint Cartilage Regeneration & Pain Relief',
              clinicalClaim: 'Significant reduction in WOMAC pain score within 14 days.',
              bulletPoints: ['Stimulates proteoglycan synthesis.', 'Inhibits cartilage-degrading enzymes.', 'Orange-flavored effervescent sachet for high compliance.'],
              dosageInfo: '1 sachet dissolved in a glass of water daily for 60 days.',
              mechanismOfAction: 'Bioactive collagen peptides stimulate chondrocyte synthesis.',
              keyUsp: 'Fast Joint Mobility Restoration • Highly Palatable',
              slideThemeColor: const Color(0xFFD97706),
              statsHighlight: {'WOMAC Pain Reduction': '-54%', 'Cartilage Thickness': '+12%', 'Compliance': '97%'},
            ),
          ],
        ),
      ];

  static List<DoctorModel> getDoctors() => [
        DoctorModel(
          id: 'doc_1',
          name: 'Dr. Chan Sopheap',
          degree: 'MD, DM (Cardiology), FACC',
          specialty: 'Interventional Cardiologist',
          doctorClass: DoctorClass.aPlus,
          practiceType: DoctorPracticeType.govtDoctor,
          clinicName: 'Calmette National Referral Hospital & Cardiac Center',
          address: 'No 3, Monivong Blvd, Srah Chak, Daun Penh, Phnom Penh',
          patch: 'Central Hospital Zone Hub',
          phone: '+855 23 426 948',
          email: 'dr.chansopheap@calmette.gov.kh',
          preferredTime: '11:00 AM - 01:00 PM',
          plannedVisitsPerMonth: 4,
          completedVisitsThisMonth: 3,
          rxPotentialMonthly: 950.0,
          taggedProductIds: ['prod_1', 'prod_2', 'prod_4'],
          keyCompetitorBrands: ['Telma-AM (Glenmark)', 'Cilacar-T (JB Chemicals)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 4)),
          birthday: '14 August',
          anniversary: '02 December',
        ),
        DoctorModel(
          id: 'doc_2',
          name: 'Dr. Sophea Seng',
          degree: 'MD (Internal Medicine), PGD (Diabetology)',
          specialty: 'Diabetologist & Physician',
          doctorClass: DoctorClass.aPlus,
          practiceType: DoctorPracticeType.clinicDoctor,
          clinicName: 'LifeCare Diabetes & Metabolic Clinic',
          address: 'No 45, Mao Tse Toung Blvd, Boeung Keng Kang, Phnom Penh',
          patch: 'BKK Central Patch A',
          phone: '+855 12 889 922',
          email: 'dr.sophea@lifecarediabetes.com.kh',
          preferredTime: '01:00 PM - 03:00 PM',
          plannedVisitsPerMonth: 3,
          completedVisitsThisMonth: 2,
          rxPotentialMonthly: 1200.0,
          taggedProductIds: ['prod_2', 'prod_1', 'prod_4'],
          keyCompetitorBrands: ['Oxra-M (Sun Pharma)', 'Forxiga (AstraZeneca)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 4)),
          birthday: '03 Nov',
          anniversary: '18 Jan',
        ),
        DoctorModel(
          id: 'doc_3',
          name: 'Dr. Vicheth Keo',
          degree: 'MS (Orthopaedics), MCh (Ortho - France)',
          specialty: 'Orthopaedic Surgeon',
          doctorClass: DoctorClass.a,
          practiceType: DoctorPracticeType.pvtDoctor,
          clinicName: 'Royal Phnom Penh Bone & Joint Center',
          address: 'No 888, Russian Hospital Blvd, Sangkat Toeuk Thla, Phnom Penh',
          patch: 'Sen Sok Medical Patch B',
          phone: '+855 23 991 000',
          email: 'vicheth.keo@royalhospital.com.kh',
          preferredTime: '06:00 PM - 08:00 PM',
          plannedVisitsPerMonth: 2,
          completedVisitsThisMonth: 1,
          rxPotentialMonthly: 850.0,
          taggedProductIds: ['prod_5', 'prod_3'],
          keyCompetitorBrands: ['Shelcal-HD (Torrent)', 'Gemcal (Alkem)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 12)),
          birthday: '19 May',
        ),
        DoctorModel(
          id: 'doc_4',
          name: 'Dr. Sovannarith Meas',
          degree: 'MD (Chest Medicine), FCCP',
          specialty: 'Pulmonologist & Hospital Specialist',
          doctorClass: DoctorClass.a,
          practiceType: DoctorPracticeType.hospitalDoctor,
          clinicName: 'Khmer-Soviet Friendship Hospital (Pulmonary Dept)',
          address: 'Street 271, Sangkat Tumnub Teuk, Chamkarmon, Phnom Penh',
          patch: 'Central Hospital Zone Hub',
          phone: '+855 23 217 764',
          email: 'dr.sovannarith@ksfh.gov.kh',
          preferredTime: '12:00 PM - 02:00 PM',
          plannedVisitsPerMonth: 2,
          completedVisitsThisMonth: 0,
          rxPotentialMonthly: 750.0,
          taggedProductIds: ['prod_3', 'prod_4'],
          keyCompetitorBrands: ['Monocef-O CV (Aristo)', 'Gudcef-CV (Mankind)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 18)),
        ),
        DoctorModel(
          id: 'doc_5',
          name: 'Dr. Bopha Chhum',
          degree: 'MD (DVL), Specialist in Dermatology',
          specialty: 'Consultant Dermatologist',
          doctorClass: DoctorClass.b,
          practiceType: DoctorPracticeType.pvtDoctor,
          clinicName: 'Aura Skin & Aesthetic Private Center',
          address: 'No 12, Norodom Blvd, Daun Penh, Phnom Penh',
          patch: 'Daun Penh Patch C',
          phone: '+855 16 772 334',
          preferredTime: '04:30 PM - 06:30 PM',
          plannedVisitsPerMonth: 2,
          completedVisitsThisMonth: 1,
          rxPotentialMonthly: 600.0,
          taggedProductIds: ['prod_3', 'prod_4'],
          keyCompetitorBrands: ['Macpod-CV (Macleods)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 8)),
        ),
        DoctorModel(
          id: 'doc_6',
          name: 'Dr. Piseth Ouk',
          degree: 'MBBS, MD (General Medicine)',
          specialty: 'Consultant Physician',
          doctorClass: DoctorClass.b,
          practiceType: DoctorPracticeType.clinicDoctor,
          clinicName: 'Central Polyclinic & Diagnostic',
          address: 'No 78, Street 1986, Sen Sok, Phnom Penh',
          patch: 'Sen Sok Medical Patch B',
          phone: '+855 11 445 566',
          preferredTime: '07:00 PM - 09:00 PM',
          plannedVisitsPerMonth: 2,
          completedVisitsThisMonth: 0,
          rxPotentialMonthly: 550.0,
          taggedProductIds: ['prod_1', 'prod_4', 'prod_3'],
          keyCompetitorBrands: ['Pantocid-DSR (Sun)', 'Telpres-AM (Abbott)'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 22)),
        ),
      ];

  static List<ChemistModel> getChemists() => [
        ChemistModel(
          id: 'chem_1',
          name: 'Haresh Patel',
          shopName: 'Nobel Medical & General Store',
          address: 'Opp. Apex Heart Clinic, Hill Road, Bandra West',
          patch: 'Bandra West Patch A',
          phone: '+91 98201 99887',
          drugLicenseNo: 'DL-20B/21B-44120',
          mappedStockistId: 'stk_1',
          mappedStockistName: 'Apex Pharma Distributors',
          avgMonthlyOrderValue: 45000,
          keyPrescribingDoctorIds: ['doc_1', 'doc_3'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 5)),
        ),
        ChemistModel(
          id: 'chem_2',
          name: 'Sunil Shah',
          shopName: 'Lifeline Chemist & Druggist',
          address: 'Shop 3, Linking Road Corner, Khar West',
          patch: 'Khar West Patch B',
          phone: '+91 98190 66554',
          drugLicenseNo: 'DL-20B/21B-55231',
          mappedStockistId: 'stk_2',
          mappedStockistName: 'Medico Lifeline Wholesale',
          avgMonthlyOrderValue: 60000,
          keyPrescribingDoctorIds: ['doc_2', 'doc_6'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 3)),
        ),
        ChemistModel(
          id: 'chem_3',
          name: 'Pravin Jain',
          shopName: 'Wellness Forever 24x7 Pharmacy',
          address: 'Waterfield Road, Bandra West, Mumbai',
          patch: 'Bandra West Patch A',
          phone: '+91 98210 33221',
          drugLicenseNo: 'DL-20B/21B-66789',
          mappedStockistId: 'stk_1',
          mappedStockistName: 'Apex Pharma Distributors',
          avgMonthlyOrderValue: 85000,
          keyPrescribingDoctorIds: ['doc_1', 'doc_5', 'doc_3'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 1)),
        ),
        ChemistModel(
          id: 'chem_4',
          name: 'Dinesh Gupta',
          shopName: 'Apollo Medplus Pharmacy',
          address: 'Near Railway Station, Santacruz West',
          patch: 'Santacruz West Patch C',
          phone: '+91 98711 22334',
          drugLicenseNo: 'DL-20B/21B-77890',
          mappedStockistId: 'stk_3',
          mappedStockistName: 'Global Health Wholesale Link',
          avgMonthlyOrderValue: 35000,
          keyPrescribingDoctorIds: ['doc_4'],
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 12)),
        ),
      ];

  static List<StockistModel> getStockists() => [
        StockistModel(
          id: 'stk_1',
          agencyName: 'Apex Pharma Distributors',
          name: 'Manish Agarwal',
          address: 'Gala 14, Sunrise Industrial Estate, Saki Naka, Andheri East, Mumbai',
          phone: '+91 98200 44556',
          email: 'apex.pharma@distributors.in',
          gstNumber: '27AAAAA1234A1Z5',
          creditLimit: 500000,
          outstandingBalance: 142500,
          paymentTermsDays: 21,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 7)),
        ),
        StockistModel(
          id: 'stk_2',
          agencyName: 'Medico Lifeline Wholesale',
          name: 'Ramesh Kothari',
          address: 'Unit 3, Kothari Chambers, Princess Street, Mumbai',
          phone: '+91 98199 88776',
          email: 'medico.lifeline@kothari.com',
          gstNumber: '27BBBBB5678B2Z6',
          creditLimit: 750000,
          outstandingBalance: 285000,
          paymentTermsDays: 30,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 12)),
        ),
        StockistModel(
          id: 'stk_3',
          agencyName: 'Global Health Wholesale Link',
          name: 'Nitin Sanghvi',
          address: '22, Sanghvi Compound, LBS Marg, Kurla West, Mumbai',
          phone: '+91 98330 11447',
          email: 'globalhealth@sanghvi.in',
          gstNumber: '27CCCCC9012C3Z7',
          creditLimit: 400000,
          outstandingBalance: 98000,
          paymentTermsDays: 15,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 19)),
        ),
      ];

  static List<SampleInventoryItem> getSampleInventory() => [
        SampleInventoryItem(
          id: 'smp_1',
          productId: 'prod_1',
          itemName: 'CardioVasc-AM (Physician Sample)',
          batchNumber: 'CV-24089',
          expiryDate: '11/2027',
          type: ItemType.sample,
          openingBalance: 60,
          allocatedQuantity: 60,
          distributedQuantity: 15,
          unit: 'Catch Covers (2 Tabs)',
        ),
        SampleInventoryItem(
          id: 'smp_2',
          productId: 'prod_2',
          itemName: 'GlycoSmart-D10 (Physician Sample)',
          batchNumber: 'GS-99120',
          expiryDate: '09/2027',
          type: ItemType.sample,
          openingBalance: 40,
          allocatedQuantity: 40,
          distributedQuantity: 10,
          unit: 'Catch Covers (4 Tabs)',
        ),
        SampleInventoryItem(
          id: 'smp_3',
          productId: 'prod_3',
          itemName: 'Cefomax-CV 325 (Physician Sample)',
          batchNumber: 'CX-88310',
          expiryDate: '01/2028',
          type: ItemType.sample,
          openingBalance: 70,
          allocatedQuantity: 70,
          distributedQuantity: 20,
          unit: 'Strips (4 Tabs)',
        ),
        SampleInventoryItem(
          id: 'smp_4',
          productId: 'prod_4',
          itemName: 'PanSafe-DSR (Physician Sample)',
          batchNumber: 'PS-11405',
          expiryDate: '06/2027',
          type: ItemType.sample,
          openingBalance: 80,
          allocatedQuantity: 80,
          distributedQuantity: 20,
          unit: 'Strips (4 Caps)',
        ),
        SampleInventoryItem(
          id: 'promo_1',
          productId: 'prod_1',
          itemName: 'CardioVasc Table Top Pen Stand with Digital Clock',
          batchNumber: 'GFT-2026-A',
          expiryDate: 'N/A',
          type: ItemType.promoGift,
          openingBalance: 15,
          allocatedQuantity: 15,
          distributedQuantity: 4,
          unit: 'Units',
        ),
        SampleInventoryItem(
          id: 'promo_2',
          productId: 'prod_2',
          itemName: 'GlycoSmart Leatherette Prescription Pad Folders',
          batchNumber: 'GFT-2026-B',
          expiryDate: 'N/A',
          type: ItemType.promoGift,
          openingBalance: 20,
          allocatedQuantity: 20,
          distributedQuantity: 6,
          unit: 'Units',
        ),
      ];

  static List<TourPlanDay> getTourPlans() {
    final now = DateTime.now();
    return [
      TourPlanDay(
        id: 'tp_today',
        date: now,
        dayType: 'Field Work (HQ)',
        patchName: 'Central Hospital Zone Hub',
        status: 'Approved',
        plannedVisits: [
          PlannedVisitItem(
            entityId: 'doc_1',
            entityName: 'Dr. Rajesh Sharma',
            entityType: 'Doctor',
            specialtyOrClass: 'Cardiologist (Class A+)',
            plannedObjective: 'Detail CardioVasc-AM & share clinical trial evidence',
            focusProducts: const ['CardioVasc-AM', 'GlycoSmart-D10'],
          ),
          PlannedVisitItem(
            entityId: 'chem_1',
            entityName: 'Sai Medicos & Pharmacy Depot',
            entityType: 'Retailer (Chemist)',
            specialtyOrClass: 'Class A Retail Pharmacy',
            plannedObjective: 'Book POB order for CardioVasc & audit prescription movement',
            focusProducts: const ['CardioVasc-AM', 'PanSafe-DSR'],
          ),
          PlannedVisitItem(
            entityId: 'fac_4',
            entityName: 'Ang Duong Advanced Poly-Clinic',
            entityType: 'Private Clinic',
            specialtyOrClass: 'Private Poly-Clinic (30 Beds)',
            plannedObjective: 'Meet consulting physicians and secure formulary recommendations',
            focusProducts: const ['CardioVasc-AM', 'Lubrica-Forte'],
          ),
          PlannedVisitItem(
            entityId: 'fac_2',
            entityName: 'Royal Phnom Penh Multi-Specialty Hospital',
            entityType: 'Hospital',
            specialtyOrClass: 'Multi-Specialty Hospital (200 Beds)',
            plannedObjective: 'Hospital procurement rate review & pharmacy stock check',
            focusProducts: const ['Lubrica-Forte', 'Cefomax-CV 325'],
          ),
          PlannedVisitItem(
            entityId: 'fac_1',
            entityName: 'Calmette National Referral Hospital',
            entityType: 'Govt Hospital',
            specialtyOrClass: 'Govt Super-Specialty Hospital (450 Beds)',
            plannedObjective: 'Follow up on institutional tender supply & CMO interaction',
            focusProducts: const ['CardioVasc-AM', 'OsteoFlex-D3 Max'],
          ),
          PlannedVisitItem(
            entityId: 'stk_1',
            entityName: 'Apollo Pharma Wholesale Depot',
            entityType: 'Stockist',
            specialtyOrClass: 'Primary Wholesale Distributor',
            plannedObjective: 'Stock replenishment review & collection statement',
            focusProducts: const ['All Brand Portfolio'],
          ),
        ],
      ),
      TourPlanDay(
        id: 'tp_tomorrow',
        date: now.add(const Duration(days: 1)),
        dayType: 'Field Work (HQ)',
        patchName: 'North Medical Corridor Patch',
        status: 'Approved',
        isJointWork: true,
        jointWithManager: 'Rajesh Sharma (Area Sales Manager)',
        plannedVisits: [
          PlannedVisitItem(
            entityId: 'doc_2',
            entityName: 'Dr. Priya Nair',
            entityType: 'Doctor',
            specialtyOrClass: 'Diabetologist (Class A+)',
            plannedObjective: 'Joint visit with ASM for GlycoSmart-D10 bulk lock',
            focusProducts: const ['GlycoSmart-D10', 'CardioVasc-AM'],
          ),
          PlannedVisitItem(
            entityId: 'chem_2',
            entityName: 'Central City Chemist & Pharmacy',
            entityType: 'Retailer (Chemist)',
            specialtyOrClass: 'Class A Retail Counter',
            plannedObjective: 'POB order collection and stockist delivery status',
            focusProducts: const ['GlycoSmart-D10', 'PanSafe-DSR'],
          ),
          PlannedVisitItem(
            entityId: 'fac_3',
            entityName: 'Daun Penh Community Health Clinic (PHC)',
            entityType: 'Govt Hospital',
            specialtyOrClass: 'Govt PHC / Dispensary (15 Beds)',
            plannedObjective: 'CMO interaction and chronic disease camp sample support',
            focusProducts: const ['GlycoSmart-D10', 'OsteoFlex-D3 Max'],
          ),
          PlannedVisitItem(
            entityId: 'stk_2',
            entityName: 'MediHealth Central Distribution',
            entityType: 'Stockist',
            specialtyOrClass: 'Primary Wholesale Distributor',
            plannedObjective: 'Distributor order forwarding and credit settlement',
            focusProducts: const ['GlycoSmart-D10'],
          ),
        ],
      ),
      TourPlanDay(
        id: 'tp_rejected_1',
        date: now.add(const Duration(days: 2)),
        dayType: 'Field Work (HQ)',
        patchName: 'East Market Route Hub',
        status: 'Rejected',
        assignedByManager: 'Rajesh Sharma (Area Sales Manager)',
        managerRemarks: 'Rejected by ASM: Route overlaps with Regional Clinical Symposium. Please reschedule for East Market Patch and add Dr. Ananya Sen.',
        plannedVisits: [
          PlannedVisitItem(
            entityId: 'doc_3',
            entityName: 'Dr. Vicheth Keo',
            entityType: 'Doctor',
            specialtyOrClass: 'Orthopaedic Surgeon (Class A)',
            plannedObjective: 'Detail OsteoFlex-D3 Max and trial study',
            focusProducts: const ['OsteoFlex-D3 Max'],
          ),
          PlannedVisitItem(
            entityId: 'chem_1',
            entityName: 'Sai Medicos & Pharmacy Depot',
            entityType: 'Retailer (Chemist)',
            specialtyOrClass: 'Class A Retail Counter',
            plannedObjective: 'POB Order Settlement',
            focusProducts: const ['PanSafe-DSR'],
          ),
        ],
      ),
      TourPlanDay(
        id: 'tp_pending_1',
        date: now.add(const Duration(days: 3)),
        dayType: 'Field Work (HQ)',
        patchName: 'South Zone Territory',
        status: 'Pending Manager Approval',
        assignedByManager: 'Self-Scheduled (Awaiting ASM Review)',
        managerRemarks: 'Submitted by MR for upcoming week itinerary validation.',
        plannedVisits: [
          PlannedVisitItem(
            entityId: 'doc_4',
            entityName: 'Dr. Sovannarith Meas',
            entityType: 'Doctor',
            specialtyOrClass: 'Pulmonologist (Class A)',
            plannedObjective: 'Present clinical trials for respiratory portfolio',
            focusProducts: const ['Cefomax-CV 325', 'PanSafe-DSR'],
          ),
          PlannedVisitItem(
            entityId: 'fac_1',
            entityName: 'Calmette National Referral Hospital',
            entityType: 'Govt Hospital',
            specialtyOrClass: 'Govt Super-Specialty Hospital (450 Beds)',
            plannedObjective: 'Institutional tender supply follow-up',
            focusProducts: const ['CardioVasc-AM'],
          ),
        ],
      ),
    ];
  }

  static List<DailyDcrSummary> getSampleDcrHistory() {
    final now = DateTime.now();
    return [
      DailyDcrSummary(
        id: 'dcr_hist_1',
        date: now.subtract(const Duration(days: 1)),
        workType: 'Field Work',
        routePatch: 'Central Hospital Zone Hub',
        status: 'Approved',
        submittedAt: now.subtract(const Duration(days: 1, hours: 4)),
        reviewedAt: now.subtract(const Duration(days: 1, hours: 2)),
        reviewedByManager: 'Rajesh Sharma (Area Sales Manager)',
        managerRemark: '✓ Approved: All 4 hospital doctor detailing calls verified. Excellent sampling compliance on CardioVasc-AM and GlycoSmart-D10.',
        totalPobValue: 0.0,
        dayRemarks: 'Completed 4 hospital and clinic visits in Central Phnom Penh. High interest in Dapagliflozin combination.',
        doctorCalls: [
          DoctorCallReport(
            id: 'call_101',
            doctorId: 'doc_1',
            doctorName: 'Dr. Chan Sopheap',
            doctorSpecialty: 'Interventional Cardiologist',
            clinicName: 'Calmette National Referral Hospital',
            doctorClass: 'A+',
            callTime: now.subtract(const Duration(days: 1, hours: 6)),
            visitType: 'Solo',
            productsPromoted: [
              ProductPromotionEntry(productId: 'prod_1', brandName: 'CardioVasc-AM', focusLevel: 'Primary', timeSpentSeconds: 180),
              ProductPromotionEntry(productId: 'prod_2', brandName: 'GlycoSmart-D10', focusLevel: 'Secondary', timeSpentSeconds: 120),
            ],
            samplesGiven: [SampleGivenEntry(productId: 'prod_1', brandName: 'CardioVasc-AM', batchNumber: 'CV-2026-A1', quantity: 4)],
            prescriptionCommitment: 'High (5+ Rx/day)',
            doctorFeedback: 'Prescribing for newly diagnosed hypertensive patients with metabolic syndrome.',
            nextVisitDate: now.add(const Duration(days: 7)),
            isGeoVerified: true,
          ),
          DoctorCallReport(
            id: 'call_102',
            doctorId: 'doc_2',
            doctorName: 'Dr. Sophea Seng',
            doctorSpecialty: 'Diabetologist & Physician',
            clinicName: 'LifeCare Diabetes & Metabolic Clinic',
            doctorClass: 'A+',
            callTime: now.subtract(const Duration(days: 1, hours: 4)),
            visitType: 'Solo',
            productsPromoted: [
              ProductPromotionEntry(productId: 'prod_2', brandName: 'GlycoSmart-D10', focusLevel: 'Primary', timeSpentSeconds: 160),
            ],
            samplesGiven: [SampleGivenEntry(productId: 'prod_2', brandName: 'GlycoSmart-D10', batchNumber: 'GS-99120', quantity: 3)],
            prescriptionCommitment: 'High (5+ Rx/day)',
            doctorFeedback: 'Impressed with 24-hour glycemic and renal protection data.',
            nextVisitDate: now.add(const Duration(days: 10)),
            isGeoVerified: true,
          ),
        ],
      ),
      DailyDcrSummary(
        id: 'dcr_hist_2',
        date: now.subtract(const Duration(days: 2)),
        workType: 'Field Work',
        routePatch: 'Sen Sok Medical Patch B',
        status: 'Rejected',
        submittedAt: now.subtract(const Duration(days: 2, hours: 5)),
        reviewedAt: now.subtract(const Duration(days: 2, hours: 1)),
        reviewedByManager: 'Rajesh Sharma (Area Sales Manager)',
        managerRemark: '⚠️ REJECTED: Dr. Vicheth Keo & Dr. Piseth Ouk visit notes are incomplete. Missing physician sample batch numbers and Rx commitment details. Please update and resubmit.',
        totalPobValue: 0.0,
        dayRemarks: 'Sen Sok patch field calls conducted. Detailed Lubrica-Forte.',
        doctorCalls: [
          DoctorCallReport(
            id: 'call_201',
            doctorId: 'doc_3',
            doctorName: 'Dr. Vicheth Keo',
            doctorSpecialty: 'Orthopaedic Surgeon',
            clinicName: 'Royal Phnom Penh Bone & Joint Center',
            doctorClass: 'A',
            callTime: now.subtract(const Duration(days: 2, hours: 6)),
            visitType: 'Solo',
            productsPromoted: [
              ProductPromotionEntry(productId: 'prod_6', brandName: 'Lubrica-Forte', focusLevel: 'Primary', timeSpentSeconds: 140),
            ],
            samplesGiven: [SampleGivenEntry(productId: 'prod_6', brandName: 'Lubrica-Forte', batchNumber: 'LF-2026-X', quantity: 2)],
            prescriptionCommitment: 'Moderate (2-4 Rx/day)',
            doctorFeedback: 'Feedback pending follow up.',
            nextVisitDate: now.add(const Duration(days: 5)),
            isGeoVerified: true,
          ),
        ],
      ),
      DailyDcrSummary(
        id: 'dcr_hist_3',
        date: now.subtract(const Duration(days: 3)),
        workType: 'Field Work',
        routePatch: 'Daun Penh Patch C',
        status: 'Submitted',
        submittedAt: now.subtract(const Duration(days: 3, hours: 3)),
        reviewedByManager: 'Rajesh Sharma (Area Sales Manager)',
        managerRemark: '⏳ Pending Manager Review: Waiting for ASM territory verification.',
        totalPobValue: 0.0,
        dayRemarks: 'Skin clinic & aesthetic center calls completed.',
        doctorCalls: [
          DoctorCallReport(
            id: 'call_301',
            doctorId: 'doc_5',
            doctorName: 'Dr. Bopha Chhum',
            doctorSpecialty: 'Consultant Dermatologist',
            clinicName: 'Aura Skin & Aesthetic Private Center',
            doctorClass: 'B',
            callTime: now.subtract(const Duration(days: 3, hours: 4)),
            visitType: 'Solo',
            productsPromoted: [
              ProductPromotionEntry(productId: 'prod_3', brandName: 'Cefomax-CV 325', focusLevel: 'Primary', timeSpentSeconds: 150),
            ],
            samplesGiven: [SampleGivenEntry(productId: 'prod_3', brandName: 'Cefomax-CV 325', batchNumber: 'CF-4410', quantity: 2)],
            prescriptionCommitment: 'Moderate (2-4 Rx/day)',
            doctorFeedback: 'Trial prescribed for acute skin and soft tissue cases.',
            nextVisitDate: now.add(const Duration(days: 12)),
            isGeoVerified: true,
          ),
        ],
      ),
    ];
  }

  static List<PobOrderModel> getSampleOrders() {
    final now = DateTime.now();
    return [
      PobOrderModel(
        id: 'ord_1',
        orderNumber: 'POB-2026-0891',
        chemistId: 'chem_1',
        chemistName: 'Mr. Chan Veasna',
        chemistShopName: 'Sai Medicos & Pharmacy Depot',
        stockistId: 'stk_1',
        stockistAgencyName: 'Apollo Pharma Wholesale Depot',
        orderDate: now.subtract(const Duration(days: 2)),
        status: 'Dispatched',
        paymentTerms: '15 Days Credit',
        remarks: 'Deliver before 4 PM urgently.',
        items: [
          OrderItem(productId: 'prod_1', brandName: 'CardioVasc-AM', packing: '10 x 10 Blister Pack', ptr: 10.50, quantity: 30, freeQuantity: 3, discountPercent: 2.0, gstPercent: 10.0),
          OrderItem(productId: 'prod_4', brandName: 'PanSafe-DSR', packing: '10 x 10 Alu-Alu Pack', ptr: 10.20, quantity: 20, freeQuantity: 2, discountPercent: 0.0, gstPercent: 10.0),
        ],
      ),
      PobOrderModel(
        id: 'ord_2',
        orderNumber: 'POB-2026-0892',
        chemistId: 'chem_2',
        chemistName: 'Ms. Keo Sreymom',
        chemistShopName: 'Central City Chemist & Pharmacy',
        stockistId: 'stk_2',
        stockistAgencyName: 'MediHealth Central Distribution',
        orderDate: now.subtract(const Duration(days: 1)),
        status: 'Forwarded to Stockist',
        paymentTerms: '30 Days Credit',
        remarks: 'New launch GlycoSmart stock needed.',
        items: [
          OrderItem(productId: 'prod_2', brandName: 'GlycoSmart-D10', packing: '10 x 10 Alu-Alu Pack', ptr: 16.80, quantity: 25, freeQuantity: 5, discountPercent: 3.0, gstPercent: 10.0),
        ],
      ),
    ];
  }

  static List<RcpaModel> getSampleRcpa() {
    final now = DateTime.now();
    return [
      RcpaModel(
        id: 'rcpa_1',
        doctorId: 'doc_1',
        doctorName: 'Dr. Rajesh Sharma',
        doctorSpecialty: 'Cardiologist',
        chemistId: 'chem_1',
        chemistShopName: 'Sai Medicos & Pharmacy Depot',
        auditDate: now.subtract(const Duration(days: 2)),
        observations: 'Dr. Sharma has shifted 40% Telma-AM prescriptions to CardioVasc-AM.',
        comparisons: [
          RcpaBrandComparison(ownBrandId: 'prod_1', ownBrandName: 'CardioVasc-AM', ownBrandRxCount: 42, ownBrandPrice: 14.50, competitorBrandName: 'Telma-AM', competitorCompany: 'Glenmark', competitorRxCount: 38, competitorPrice: 17.20),
          RcpaBrandComparison(ownBrandId: 'prod_2', ownBrandName: 'GlycoSmart-D10', ownBrandRxCount: 28, ownBrandPrice: 23.50, competitorBrandName: 'Forxiga 10', competitorCompany: 'AstraZeneca', competitorRxCount: 35, competitorPrice: 31.00),
        ],
      ),
    ];
  }

  static List<DailyExpenseClaim> getSampleExpenses() {
    final now = DateTime.now();
    return [
      DailyExpenseClaim(
        id: 'exp_1',
        date: now.subtract(const Duration(days: 1)),
        workPlaceType: WorkPlaceType.hq,
        routeCovered: 'Monivong Blvd - Daun Penh - Central Hub',
        travelDistanceKm: 32.0,
        ratePerKm: 0.25,
        dailyAllowance: 15.0,
        fuelAmount: 8.0,
        foodAmount: 5.5,
        status: 'Approved',
        managerRemarks: 'Verified against GPS logs and chemist POB records. Approved for reimbursement.',
        submittedAt: now.subtract(const Duration(days: 1)),
        billPhotoName: 'Fuel_Tela_Monivong_Receipt.jpg',
        miscExpenses: [
          MiscExpenseItem(title: 'Hospital Parking & Toll', amount: 2.0, category: ExpenseCategory.misc),
        ],
      ),
      DailyExpenseClaim(
        id: 'exp_2',
        date: now.subtract(const Duration(days: 2)),
        workPlaceType: WorkPlaceType.exHq,
        routeCovered: 'Phnom Penh - Toul Kork - Russian Blvd',
        travelDistanceKm: 48.0,
        ratePerKm: 0.25,
        dailyAllowance: 20.0,
        fuelAmount: 12.0,
        taxiAmount: 6.0,
        foodAmount: 7.0,
        status: 'Submitted',
        submittedAt: now.subtract(const Duration(days: 2)),
        billPhotoName: 'PassApp_Taxi_ToulKork_Bill.jpg',
        miscExpenses: [
          MiscExpenseItem(title: 'Clinic Parking Fee', amount: 1.5, category: ExpenseCategory.misc),
        ],
      ),
      DailyExpenseClaim(
        id: 'exp_3',
        date: now.subtract(const Duration(days: 4)),
        workPlaceType: WorkPlaceType.outstation,
        routeCovered: 'Mumbai HQ - Pune Outstation - Nashik Belt',
        travelDistanceKm: 156.0,
        ratePerKm: 0.25,
        dailyAllowance: 35.0,
        fuelAmount: 0.0,
        taxiAmount: 18.0,
        hotelLodging: 45.0,
        foodAmount: 12.0,
        trainAmount: 22.0,
        status: 'Rejected',
        managerRemarks: 'Hotel bill exceeds policy limit of ₹1,500/night. Please attach original GST invoice and resubmit with corrected amount.',
        submittedAt: now.subtract(const Duration(days: 4)),
        billPhotoName: 'Hotel_PuneStay_Invoice.jpg',
        miscExpenses: [
          MiscExpenseItem(title: 'Toll & Parking – Nashik Highway', amount: 8.0, category: ExpenseCategory.misc),
        ],
      ),
    ];
  }

  static List<FacilityModel> getFacilities() => [
        FacilityModel(
          id: 'fac_1',
          name: 'Calmette National Referral Hospital & Medical Center',
          category: FacilityCategory.hospital,
          sector: FacilitySector.government,
          address: 'No 3, Monivong Blvd, Srah Chak, Daun Penh, Phnom Penh',
          patch: 'Central Hospital Zone Hub',
          phone: '+855 23 426 948',
          contactPerson: 'Dr. Heng Seng (Medical Director)',
          designation: 'Superintendent & Purchase In-charge',
          totalBeds: 450,
          visitingDoctorNames: ['Dr. Rajesh Sharma', 'Dr. Sokha Meas', 'Dr. Priya Nair'],
          monthlyPotential: 3500.0,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 3)),
          notes: 'Bulk hospital tender for CardioVasc-AM and Cefomax-CV approved.',
        ),
        FacilityModel(
          id: 'fac_2',
          name: 'Royal Phnom Penh Multi-Specialty Hospital',
          category: FacilityCategory.hospital,
          sector: FacilitySector.private,
          address: 'No 888, Russian Confederation Blvd, Toul Kork, Phnom Penh',
          patch: 'North Medical Corridor Patch',
          phone: '+855 23 991 000',
          contactPerson: 'Ms. Chan Veasna (Pharmacy Head)',
          designation: 'Head of Clinical Procurement',
          totalBeds: 200,
          visitingDoctorNames: ['Dr. Priya Nair', 'Dr. Sokha Meas'],
          monthlyPotential: 2800.0,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 1)),
          notes: 'High volume outpatient orthopedic and cardiology prescriptions.',
        ),
        FacilityModel(
          id: 'fac_3',
          name: 'Daun Penh Community Health Clinic (PHC)',
          category: FacilityCategory.govtDispensary,
          sector: FacilitySector.government,
          address: 'Street 130, Daun Penh District, Phnom Penh',
          patch: 'East Market Route Hub',
          phone: '+855 23 724 112',
          contactPerson: 'Dr. Chea Sovann',
          designation: 'Chief Medical Officer',
          totalBeds: 15,
          visitingDoctorNames: ['Dr. Chea Sovann'],
          monthlyPotential: 650.0,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 5)),
          notes: 'Govt health clinic with steady chronic diabetic and hypertension patients.',
        ),
        FacilityModel(
          id: 'fac_4',
          name: 'Ang Duong Advanced Poly-Clinic & Diagnostics',
          category: FacilityCategory.polyClinic,
          sector: FacilitySector.private,
          address: 'Street 271, Boeng Tumpun, Meanchey, Phnom Penh',
          patch: 'South Zone Territory',
          phone: '+855 23 883 456',
          contactPerson: 'Dr. Kim San (Director)',
          designation: 'Managing Director & Consultant',
          totalBeds: 30,
          visitingDoctorNames: ['Dr. Kim San', 'Dr. Rajesh Sharma'],
          monthlyPotential: 1200.0,
          lastVisitedDate: DateTime.now().subtract(const Duration(days: 2)),
          notes: 'Private polyclinic with 8 visiting consultants daily.',
        ),
      ];
}
